language: python
node_js:
  - "9.11.2"
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - npm install -g
# command to run tests
script:
  - flake8 apps/
  - python -Wall apps/manage.py test -v 2 movies
  - coverage3 run --source='./apps' --omit='*migrations*' apps/manage.py test movies
  - coverage3 report -m
  - jshint apps/movies/static/movies/js/
  - jshint apps/movies/static/movies/test/spec
  - csslint apps/movies/static/movies/css/app.css
  - htmlhint --config htmlhint.conf apps/movies/templates/movies/index.html
  - htmlhint --config htmlhint.conf apps/movies/static/movies/partials/
  - css-beautify -r apps/movies/static/movies/css/app.css
  - html-beautify -r apps/movies/templates/movies/index.html
  - html-beautify -r apps/movies/static/movies/partials/*.html
  - js-beautify -r apps/movies/static/movies/js/*.js
  - phantomjs -v
  - karma start --single-run
after_success:
  - coveralls
