language: python
node_js:
  - "9"
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - npm install --only=dev
# command to run tests
script:
  - flake8 apps/
  - python -Wall apps/manage.py test -v 2 movies
  - coverage3 run --source='./apps' --omit='*migrations*' apps/manage.py test movies
  - coverage3 report -m
  - node -v
  - npm -v
  - node_modules/.bin/jshint apps/movies/static/movies/js/
  - node_modules/.bin/jshint apps/movies/static/movies/test/spec
  - node_modules/.bin/csslint apps/movies/static/movies/css/app.css
  - node_modules/.bin/htmlhint --config htmlhint.conf apps/movies/templates/movies/index.html
  - node_modules/.bin/htmlhint --config htmlhint.conf apps/movies/static/movies/partials/
  - node_modules/.bin/css-beautify -r apps/movies/static/movies/css/app.css
  - node_modules/.bin/html-beautify -r apps/movies/templates/movies/index.html
  - node_modules/.bin/html-beautify -r apps/movies/static/movies/partials/*.html
  - node_modules/.bin/js-beautify -r apps/movies/static/movies/js/*.js
  - phantomjs -v
  - node_modules/karma/bin/karma start --single-run
after_success:
  - coveralls
