# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160705_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='media/movies/Movie.jpg', upload_to='media/movies/'),
        ),
    ]
