# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movies/Movie.jpg', upload_to='movies/'),
        ),
    ]
