# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
