# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(default='', max_length=400),
        ),
    ]
