# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='movies.MovieGenre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
    ]
