# Generated by Django 2.1.2 on 2018-10-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20180413_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='small_image',
            field=models.ImageField(default='movies/small/Movie.jpg', upload_to='movies/small/'),
        ),
    ]
